# Generated by Django 4.0.3 on 2022-03-29 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcf', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('orders', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tcf.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcf.product')),
            ],
        ),
    ]
